# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Podtube' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Podtube
    pod 'Alamofire', '~> 4.5'
    pod 'SDWebImage', '~> 4.0'
  target 'PodtubeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PodtubeUITests' do
    # Pods for testing
    
  end

end
